# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BU CS 506
tagline: Data Science Tools and Applications
description: Course website for Boston University CS 506 - Data Science Tools and Applications
author: Lance Galletti
url: 'https://gallettilance.github.io/'
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.3.3
color_scheme: dark
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Piazza:
    - 'https://piazza.com/bu/spring2023/cs506'
  GradeScope:
    - 'https://www.gradescope.com/courses/495203'
  GitHub:
    - 'https://github.com/gallettilance/CS506-Spring2023'
  Discord:
    - 'https://discord.gg/5Xf9gQ6z'
footer_content:

# Collections for website data
collections:
  staffers:
  modules:
  assignments:
  faq:
  deliverables:

# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      subpath: '/assets/images/'
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: assignments
    values:
      layout: module
  - scope:
      path: ''
      type: faq
    values:
      layout: module
  - scope:
      path: ''
      type: deliverables
    values:
      layout: module
  

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

plugins:
  - jekyll-seo-tag
